[package]
name = "olc-longest-path"
version = "0.1.0"
authors = ["Martin MunÌƒoz <im.mmun@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"
